exports.products = [
    {
        name: 'Airpods Wireless Headphones',
        image: '/images/airpods.jpg',
        description: 'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
        brand: 'Apple',
        category: 'Headphones',
        price: 89.99,
        countInStock: 10,
        rating: 3.5,
        numReviews: 12,
    },
    {
        name: 'iPhone 12 Max Pro',
        image: '/images/iphone12maxpro.jpg',
        description: 'Introducing the iPhone 12 Max Pro. A transformative camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
        brand: 'Apple',
        category: 'Phones',
        price: 1199.99,
        countInStock: 7,
        rating: 4.0,
        numReviews: 8,
    },
    {
        name: 'Sony A7 III Camera',
        image: '/images/sony-a7.jpg',
        description: 'Characterized by versatile imaging specs, the Sony A7 III further clarifies itself using a pair of robust focusing systems and an intuitive design',
        brand: 'Sony',
        category: 'Camera',
        price: 1999.99,
        countInStock: 5,
        rating: 4.5,
        numReviews: 12,
    },
    {
        name: 'Sony Playstation 5',
        image: '/images/playstation.jpg',
        description: 'The ultimate home entertainment center starts with PlayStation. Whether you are into gaming, HD movies, television, music',
        brand: 'Sony',
        category: 'Console',
        price: 399.99,
        countInStock: 11,
        rating: 5,
        numReviews: 12,
    },
    {
        name: 'Xiaomi Smartwatch',
        image: '/images/xiaomi-smartwatch.jpg',
        description: 'The all-day Always-On Display* feature can display time, even in direct sunlight. Clearly displays incoming calls, notifications, fitness, and other important information.',
        brand: 'Xiaomi',
        category: 'Smartwatch',
        price: 99.99,
        countInStock: 0,
        rating: 3.5,
        numReviews: 10,
    },
    {
        name: 'HP Laserjet Printer',
        image: '/images/hp-printer.jpg',
        description: 'Perfect for office and home work. HP LaserJets have unmatched printing speed, performance and reliability that you can trust.',
        brand: 'HP',
        category: 'Printer',
        price: 399.99,
        countInStock: 7,
        rating: 4.5,
        numReviews: 10,
    }
]